const express = require("express");
const registerUser = require("../controller/registerUser");
const jwtController = require("../controller/jwtControler");
const postData = require("../controller/postData");
const getData = require("../controller/getData");
const addAvatar = require("../controller/addAvatar");
const logInUser = require("../controller/loginUser");
const signupRouter = express.Router();
const loginRouter = express.Router();
const dataRouter = express.Router();
signupRouter.route("/signup").post(registerUser);
loginRouter.route("/login").post(logInUser);
dataRouter.route("/data").post(jwtController, postData);
dataRouter.route("/data").get(jwtController, getData);
dataRouter.route("/avatar").patch(jwtController, addAvatar);
module.exports = { signupRouter, dataRouter, loginRouter };
